### ISSUE TITLE
Diferentes áreas para criar ideias

### ISSUE THREAD

**Issue by mumumilk** [mumumilk/nuvem-de-ideias#7]
* __Estou enviando um...__
  - [ ] bug report
  - [x] feature request

* **Qual é o comportamento atual?**
O  app não suporta diferentes áreas para adicionar ideias

* **Se o comportamento atual é um bug, providencie os passos para reprodução do problema.** 

* **Qual é o comportamento esperado?**
O app deveria ter opção de criar e entrar em áreas diferentes e customizáveis para coletar diferentes ideias

* **Outras informações** (exemplo: explicação detalhada, issues relacionadas, sugestões..)

**Comment by picossi** [comment]
Seria algo semelhante a criação de uma organização?

**Comment by mumumilk** [comment]
@picossi acredito que a estrutura parecida seria: Uma organização tem várias áreas (rh, comercial, dev..) e uma área tem várias ideias.
